# Generated by Django 4.2 on 2023-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('talle', models.CharField(max_length=5)),
                ('diseño', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=20)),
            ],
        ),
    ]
