# Generated by Django 4.2 on 2023-04-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remera',
            old_name='diseño',
            new_name='disenio',
        ),
    ]
